name: Building macOS x86

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deps Installing
      run: brew install llvm i686-elf-gcc i686-elf-binutils ninja nasm
    
    - name: GN Installing
      run: |
        wget https://chrome-infra-packages.appspot.com/dl/gn/gn/mac-amd64/+/latest
        unzip latest
        mv gn /usr/local/bin
        
    - name: Create Build Environment
      run: gn gen out --args='target_cpu="x86" host="gnu"'

    - name: Cleaning GNU Build Environment
      run: rm -rf out

    - name: Create LLVM Build Environment
      run: |
        export LLVM_BIN_PATH="/usr/local/Cellar/llvm/12.0.1/bin"
        gn gen out --args='target_cpu="x86" host="llvm"'

    - name: Cleaning Desktop LLVM Build Environment
      run: rm -rf out

    - name: Create Mobile LLVM Build Environment
      run: |
        export LLVM_BIN_PATH="/usr/local/Cellar/llvm/12.0.1/bin"
        gn gen out --args='target_cpu="x86" host="llvm" device_type="m"'

    - name: Build GNU
      working-directory: ${{github.workspace}}/out
      shell: bash
      run: ninja

    - name: Cleaning Mobile LLVM Build Environment
      run: rm -rf out