name: Building For ARM In macOS-11

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2

      - name: Pouring Deps
        run: |
          brew install llvm ninja nasm
          brew tap pranaOS/homebrew-formulae-arm-gcc
          brew install pranaOS/homebrew-formulae-arm-gcc/arm-none-eabi-gcc

      - name: Pouring GN
        run: |
          wget https://chrome-infra-packages.appspot.com/dl/gn/gn/mac-amd64/+/latest
          unzip latest
          mv gn /usr/local/bin

      - name: Create GNU Build Environment
        run: gn gen out --args='target_cpu="aarch32" host="gnu"'

      - name: Build GNU
        working-directory: ${{github.workspace}}/out
        shell: bash
        run: ninja

      - name: Cleaning GNU Build Environment
        run: rm -rf out
