name: kernel check

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: kernel check
        shell: bash
        run: find kernel
