name: macOS C++ Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Deps Installing
        run: |
          brew update
          brew install make nasm i686-elf-gcc

      - name: Check version of tools
        run: |
          node --version
          g++ --version

      - name: Build
        run: |
          make pranaOS
        
      - name: Clean
        run: |
          make clean 

      - name: Run tests
        run: |
          node tests/dirtest.js
          node tests/checkVersion.js
